AI/Rules.js
AI/tribe.js

Just moved one line inside of the isbusy if-statement

Optimized rules algorithm, put sort inside of lock.

---

AI/tribe.js

Put in a comment in tribe to test the new git procedure

---

test/developer.js

Little timing issue, but that can be resolved

completed all of the String pull GUI

---

test/developer.js

hopefully working sliders on tablet

Touch Stuff and tribe info

---

test/developer.js

Fix stupid mistake

---

test/developer.js

unfortunate bug fixing

---

test/developer.js

4th times a charm

---

test/developer.js

unlikely fix

---

test/developer.js

reverted back to almost working

---

test/developer.js

trying the binding this fix

---

test/developer.js

TABLET TESTING

---

test/developer.js

wish there were a better way guys

Tablet Testing #87

---

test/developer.js

added unnecessary stuff that might work

One more Test

---

AI/tribe.js
Globe/Cluster.js
Globe/GlobalInterface.js
Globe/Globe.js
Globe/IcoSphere.js
Globe/Tile.js
Globe/VertexGraph.js
Globe/VertexNode.js

Refactored world generation code. Now has vertex graph and updated visuals. Will clean up code when merged

World gen refactor

---

test/developer.js

added visual Pause button

---

test/developer.js

Pause button fully functional

---

HIDInterface/HIDInterface.js
test/developer.js

fixed Pause button +made empty music slider

---

Camera/Camera.js

now it completely stops rotation and when you unpause it , it goes back
to rotating

Fixed pause button better

---

AI/tribe.js
Globe/GlobalInterface.js

Just updated to make the AI and Fault lines pause as well

Pause revisions

---

test/developer.js

starts off click button to turn on

Toggle UI on or off

---

HIDInterface/HIDInterface.js
test/developer.js

UI button fix and SLider's updating with button press

---

Audio/AudioController.js
Globe/GlobalInterface.js

It switches just needs to be balanced

Music is better

---

test/developer.js

Updated the tribe Info
